version: "3.7"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  client:
    container_name: client
    build:
      context: src/client
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_GOOGLE_MAPS_KEY=AIzaSyBz90-mDSnW2HWWWS_7zUFsy9bWAORQ82g
      - NEXT_PUBLIC_API_URL=http://api:8000
    ports:
      - "3000:3000"