name: Web Client CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/client/**'
      - '.github/workflows/service-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/client/**'
      - '.github/workflows/client-ci.yml'

env:
  NEXT_PUBLIC_GOOGLE_MAPS_KEY: test
  NEXT_PUBLIC_API_URL: http://localhost:8000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm ci
        working-directory: src/client

      - name: Lint
        run: npm run lint
        working-directory: src/client

      - name: Build
        run: npm run build
        working-directory: src/client

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd src/client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mbajk-web-client:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mbajk-web-client:latest
