name: Fetch

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:


env:
  WINDOW_SIZE: 48
  TOP_FEATURES: 4
  LAT: 46.5547
  LON: 15.6466
  MBAJK_API_KEY: ${{ secrets.MBAJK_API_KEY }}


jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install  poetry 

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Fetch data
        run: |
          poetry run poe fetch

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || (git commit -a -m "action: fetch latest data" --allow-empty)
          git push

      - name: Process data
        run: |
          poetry run poe process