name: Fetch

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  WINDOW_SIZE: 48
  TOP_FEATURES: 4
  LAT: 46.5547
  LON: 15.6466
  MBAJK_API_KEY: ${{ secrets.MBAJK_API_KEY }}

jobs:
  fetch:
    runs-on: ubuntu-latest

    outputs:
      sha_new: ${{ steps.sha_new.outputs.SHA_NEW }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install  poetry 

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Fetch data
        run: |
          poetry run poe fetch

      - name: Commit changes
        run: |
          git add .
          git commit -m "action: fetch data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get commit SHA and store it in GITHUB_OUTPUT
        id: sha_new
        run: echo "SHA_NEW=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  process:
    needs: fetch

    runs-on: ubuntu-latest

    outputs:
      sha_new: ${{ steps.sha_new.outputs.SHA_NEW }}

    permissions:
      contents: write

    steps:
      - env:
          SHA_NEW: ${{ needs.fetch.outputs.sha_new }}
        run: echo "$SHA_NEW"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.fetch.outputs.sha_new }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Prerequisites
        run: |
          python -m pip install --upgrade pip
          pip install  poetry 

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Process data
        run: |
          poetry run poe process

      - name: Commit changes
        run: |
          git add .
          git commit -m "action: process data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}