name: Data Pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  WINDOW_SIZE: 24
  TOP_FEATURES: 4
  LAT: 46.5547
  LON: 15.6466
  MBAJK_API_KEY: ${{ secrets.MBAJK_API_KEY }}
  DVC_ACCESS_KEY_ID: ${{ secrets.DVC_ACCESS_KEY_ID }}
  DVC_SECRET_ACCESS_KEY: ${{ secrets.DVC_SECRET_ACCESS_KEY }}
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}

jobs:
  fetch_weather_data:
    runs-on: ubuntu-latest

    outputs:
      sha_new: ${{ steps.sha_new.outputs.SHA_NEW }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id $DVC_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DVC_SECRET_ACCESS_KEY

      - name: DVC pull
        run: |
          dvc pull -r origin

      - name: Run Tests
        run: |
          poetry run poe test_job

      - name: Fetch weather data
        run: |
          poetry run poe fetch_weather_data

      - name: Commit changes to DVC
        run: |
          dvc add data/raw/weather.csv
          dvc push -r origin

      - name: Commit changes to GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"
          git add .
          git commit -m "action: fetch weather data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get commit SHA and store it in GITHUB_OUTPUT
        id: sha_new
        run: echo "SHA_NEW=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  fetch_bike_data:
    needs: fetch_weather_data
    runs-on: ubuntu-latest

    outputs:
      sha_new: ${{ steps.sha_new.outputs.SHA_NEW }}

    permissions:
      contents: write

    steps:
      - env:
          SHA_NEW: ${{ needs.fetch_weather_data.outputs.sha_new }}
        run: echo "$SHA_NEW"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.fetch_weather_data.outputs.sha_new }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id $DVC_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DVC_SECRET_ACCESS_KEY

      - name: DVC pull
        run: |
          dvc pull -r origin

      - name: Run Tests
        run: |
          poetry run poe test_job

      - name: Fetch bike data
        run: |
          poetry run poe fetch_bike_data

      - name: Commit changes to DVC
        run: |
          dvc add data/raw/mbajk_stations.csv
          dvc push -r origin

      - name: Commit changes to GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"
          git add .
          git commit -m "action: fetch bike data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get commit SHA and store it in GITHUB_OUTPUT
        id: sha_new
        run: echo "SHA_NEW=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

  process:
    needs: fetch_bike_data
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      sha_process: ${{ steps.sha_process.outputs.SHA_PROCESS }}

    steps:
      - env:
          SHA_NEW: ${{ needs.fetch_bike_data.outputs.sha_new }}
        run: echo "$SHA_NEW"

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.fetch_bike_data.outputs.sha_new }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id $DVC_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DVC_SECRET_ACCESS_KEY

      - name: DVC pull
        run: |
          dvc pull -r origin

      - name: Process data
        run: |
          poetry run poe process

      - name: Commit changes to DVC
        run: |
          dvc add data/processed/*.csv
          dvc push -r origin

      - name: Commit changes to GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"
          git add .
          git commit --allow-empty -m "action: process data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get commit SHA and store it in GITHUB_OUTPUT
        id: sha_process
        run: echo "SHA_PROCESS=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"


  validation:
    runs-on: ubuntu-latest
    needs:
      - process

    outputs:
      sha_new: ${{ steps.sha_new.outputs.SHA_NEW }}

    steps:
      - env:
          SHA_PROCESS: ${{ needs.process.outputs.sha_process }}
          SHA_NEW: ${{ needs.fetch_bike_data.outputs.sha_new }}
        run: |
          echo "$SHA_PROCESS" 

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.process.outputs.sha_process }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id $DVC_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DVC_SECRET_ACCESS_KEY

      - name: DVC pull
        run: |
          dvc pull -r origin

      - name: Get reference data
        run: |
          dvc get . data/processed/current_data.csv --rev $SHA_NEW --out data/processed/reference_data.csv --force

      - name: Run validation
        run: |
          poetry run poe validate

      - name: Run Data Drift
        run: |
          poetry run poe data_drift

      - name: Run Stability tests
        run: |
          poetry run poe stability_tests

      - name: Run Kolmogorov-Smirnov test
        run: |
          poetry run poe ks_test

      - name: Deploy DataDocs to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "reports/sites"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Commit changes to GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"
          git add .
          git commit -m "action: validate data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Get commit SHA and store it in GITHUB_OUTPUT
        id: sha_new
        run: echo "SHA_NEW=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"


  split_data:
    runs-on: ubuntu-latest

    needs:
      - validation

    steps:
      - env:
          SHA_NEW: ${{ needs.validation.outputs.sha_new }}
        run: echo "$SHA_NEW"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.validation.outputs.sha_new }}
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id $DVC_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DVC_SECRET_ACCESS_KEY

      - name: DVC pull
        run: |
          dvc pull -r origin

      - name: Run split data
        run: |
          poetry run poe split_data

      - name: Commit changes to DVC
        run: |
          dvc add data/processed/*.csv
          dvc push -r origin

      - name: Commit changes to GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"
          git add .
          git commit --allow-empty -m "action: train model"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}