name: test cron jobs

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"