name: Model Training Pipeline

on:
#  workflow_run:
#    workflows: [ "Data Pipeline" ]
#    types:
#      - completed
  workflow_dispatch:

env:
  WINDOW_SIZE: 24
  TOP_FEATURES: 4
  LAT: 46.5547
  LON: 15.6466
  MBAJK_API_KEY: ${{ secrets.MBAJK_API_KEY }}
  DVC_ACCESS_KEY_ID: ${{ secrets.DVC_ACCESS_KEY_ID }}
  DVC_SECRET_ACCESS_KEY: ${{ secrets.DVC_SECRET_ACCESS_KEY }}
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
  DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}


jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Temporary workaround for GitVersion
        shell: bash
        run: |
            git config extensions.worktreeconfig false

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-root

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC
        run: |
          dvc remote modify origin --local access_key_id $DVC_ACCESS_KEY_ID
          dvc remote modify origin --local secret_access_key $DVC_SECRET_ACCESS_KEY

      - name: DVC pull
        run: |
          dvc pull -r origin

      - name: Train model
        run: |
          poetry run poe train

      - name: Predict
        run: |
          poetry run poe predict

      - name: Commit changes to GIT
        run: |
          git config --global user.email "perko.domen@gmail.com"
          git config --global user.name "perkzen"
          git add .
          git commit --allow-empty -m "action: train model"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}